"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import lightning_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _LookupModifier:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _LookupModifierEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_LookupModifier.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    DEFAULT: _LookupModifier.ValueType  # 0
    """The default look up modifier, no look up behavior is changed."""
    HTLC_SET_ONLY: _LookupModifier.ValueType  # 1
    """
    Indicates that when a look up is done based on a set_id, then only that set
    of HTLCs related to that set ID should be returned.
    """
    HTLC_SET_BLANK: _LookupModifier.ValueType  # 2
    """
    Indicates that when a look up is done using a payment_addr, then no HTLCs
    related to the payment_addr should be returned. This is useful when one
    wants to be able to obtain the set of associated setIDs with a given
    invoice, then look up the sub-invoices "projected" by that set ID.
    """

class LookupModifier(_LookupModifier, metaclass=_LookupModifierEnumTypeWrapper): ...

DEFAULT: LookupModifier.ValueType  # 0
"""The default look up modifier, no look up behavior is changed."""
HTLC_SET_ONLY: LookupModifier.ValueType  # 1
"""
Indicates that when a look up is done based on a set_id, then only that set
of HTLCs related to that set ID should be returned.
"""
HTLC_SET_BLANK: LookupModifier.ValueType  # 2
"""
Indicates that when a look up is done using a payment_addr, then no HTLCs
related to the payment_addr should be returned. This is useful when one
wants to be able to obtain the set of associated setIDs with a given
invoice, then look up the sub-invoices "projected" by that set ID.
"""
global___LookupModifier = LookupModifier

@typing_extensions.final
class CancelInvoiceMsg(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAYMENT_HASH_FIELD_NUMBER: builtins.int
    payment_hash: builtins.bytes
    """Hash corresponding to the (hold) invoice to cancel. When using
    REST, this field must be encoded as base64.
    """
    def __init__(
        self,
        *,
        payment_hash: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["payment_hash", b"payment_hash"]) -> None: ...

global___CancelInvoiceMsg = CancelInvoiceMsg

@typing_extensions.final
class CancelInvoiceResp(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___CancelInvoiceResp = CancelInvoiceResp

@typing_extensions.final
class AddHoldInvoiceRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MEMO_FIELD_NUMBER: builtins.int
    HASH_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    VALUE_MSAT_FIELD_NUMBER: builtins.int
    DESCRIPTION_HASH_FIELD_NUMBER: builtins.int
    EXPIRY_FIELD_NUMBER: builtins.int
    FALLBACK_ADDR_FIELD_NUMBER: builtins.int
    CLTV_EXPIRY_FIELD_NUMBER: builtins.int
    ROUTE_HINTS_FIELD_NUMBER: builtins.int
    PRIVATE_FIELD_NUMBER: builtins.int
    memo: builtins.str
    """
    An optional memo to attach along with the invoice. Used for record keeping
    purposes for the invoice's creator, and will also be set in the description
    field of the encoded payment request if the description_hash field is not
    being used.
    """
    hash: builtins.bytes
    """The hash of the preimage"""
    value: builtins.int
    """
    The value of this invoice in satoshis

    The fields value and value_msat are mutually exclusive.
    """
    value_msat: builtins.int
    """
    The value of this invoice in millisatoshis

    The fields value and value_msat are mutually exclusive.
    """
    description_hash: builtins.bytes
    """
    Hash (SHA-256) of a description of the payment. Used if the description of
    payment (memo) is too long to naturally fit within the description field
    of an encoded payment request.
    """
    expiry: builtins.int
    """Payment request expiry time in seconds. Default is 86400 (24 hours)."""
    fallback_addr: builtins.str
    """Fallback on-chain address."""
    cltv_expiry: builtins.int
    """Delta to use for the time-lock of the CLTV extended to the final hop."""
    @property
    def route_hints(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[lightning_pb2.RouteHint]:
        """
        Route hints that can each be individually used to assist in reaching the
        invoice's destination.
        """
    private: builtins.bool
    """Whether this invoice should include routing hints for private channels."""
    def __init__(
        self,
        *,
        memo: builtins.str = ...,
        hash: builtins.bytes = ...,
        value: builtins.int = ...,
        value_msat: builtins.int = ...,
        description_hash: builtins.bytes = ...,
        expiry: builtins.int = ...,
        fallback_addr: builtins.str = ...,
        cltv_expiry: builtins.int = ...,
        route_hints: collections.abc.Iterable[lightning_pb2.RouteHint] | None = ...,
        private: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["cltv_expiry", b"cltv_expiry", "description_hash", b"description_hash", "expiry", b"expiry", "fallback_addr", b"fallback_addr", "hash", b"hash", "memo", b"memo", "private", b"private", "route_hints", b"route_hints", "value", b"value", "value_msat", b"value_msat"]) -> None: ...

global___AddHoldInvoiceRequest = AddHoldInvoiceRequest

@typing_extensions.final
class AddHoldInvoiceResp(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAYMENT_REQUEST_FIELD_NUMBER: builtins.int
    ADD_INDEX_FIELD_NUMBER: builtins.int
    PAYMENT_ADDR_FIELD_NUMBER: builtins.int
    payment_request: builtins.str
    """
    A bare-bones invoice for a payment within the Lightning Network. With the
    details of the invoice, the sender has all the data necessary to send a
    payment to the recipient.
    """
    add_index: builtins.int
    """
    The "add" index of this invoice. Each newly created invoice will increment
    this index making it monotonically increasing. Callers to the
    SubscribeInvoices call can use this to instantly get notified of all added
    invoices with an add_index greater than this one.
    """
    payment_addr: builtins.bytes
    """
    The payment address of the generated invoice. This value should be used
    in all payments for this invoice as we require it for end to end
    security.
    """
    def __init__(
        self,
        *,
        payment_request: builtins.str = ...,
        add_index: builtins.int = ...,
        payment_addr: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["add_index", b"add_index", "payment_addr", b"payment_addr", "payment_request", b"payment_request"]) -> None: ...

global___AddHoldInvoiceResp = AddHoldInvoiceResp

@typing_extensions.final
class SettleInvoiceMsg(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PREIMAGE_FIELD_NUMBER: builtins.int
    preimage: builtins.bytes
    """Externally discovered pre-image that should be used to settle the hold
    invoice.
    """
    def __init__(
        self,
        *,
        preimage: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["preimage", b"preimage"]) -> None: ...

global___SettleInvoiceMsg = SettleInvoiceMsg

@typing_extensions.final
class SettleInvoiceResp(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___SettleInvoiceResp = SettleInvoiceResp

@typing_extensions.final
class SubscribeSingleInvoiceRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    R_HASH_FIELD_NUMBER: builtins.int
    r_hash: builtins.bytes
    """Hash corresponding to the (hold) invoice to subscribe to. When using
    REST, this field must be encoded as base64url.
    """
    def __init__(
        self,
        *,
        r_hash: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["r_hash", b"r_hash"]) -> None: ...

global___SubscribeSingleInvoiceRequest = SubscribeSingleInvoiceRequest

@typing_extensions.final
class LookupInvoiceMsg(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAYMENT_HASH_FIELD_NUMBER: builtins.int
    PAYMENT_ADDR_FIELD_NUMBER: builtins.int
    SET_ID_FIELD_NUMBER: builtins.int
    LOOKUP_MODIFIER_FIELD_NUMBER: builtins.int
    payment_hash: builtins.bytes
    """When using REST, this field must be encoded as base64."""
    payment_addr: builtins.bytes
    set_id: builtins.bytes
    lookup_modifier: global___LookupModifier.ValueType
    def __init__(
        self,
        *,
        payment_hash: builtins.bytes = ...,
        payment_addr: builtins.bytes = ...,
        set_id: builtins.bytes = ...,
        lookup_modifier: global___LookupModifier.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["invoice_ref", b"invoice_ref", "payment_addr", b"payment_addr", "payment_hash", b"payment_hash", "set_id", b"set_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["invoice_ref", b"invoice_ref", "lookup_modifier", b"lookup_modifier", "payment_addr", b"payment_addr", "payment_hash", b"payment_hash", "set_id", b"set_id"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["invoice_ref", b"invoice_ref"]) -> typing_extensions.Literal["payment_hash", "payment_addr", "set_id"] | None: ...

global___LookupInvoiceMsg = LookupInvoiceMsg
